version: "3"
services:
  reactapp:
    image: reactapp
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  app:
    image: app
    ports:
      - "8080:8080"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge