
export const INIT_PREPROCESS='INIT_PREPROCESS';
export const LOGIN_FROM_CACHE='LOGIN_FROM_CACHE';
export const LOGIN_RESULT='LOGIN_RESULT';
export const LOGOUT='LOGOUT';
export const USER_CLEAR_ERROR_MESSAGE='USER_CLEAR_ERROR_MESSAGE';
export const CREATE_USER='CREATE_USER';
export const FETCH_USERS='FETCH_USERS';
export const FETCH_ROOMS='FETCH_ROOMS';
export const FETCH_CHAT='FETCH_CHAT';
export const ADD_MESSAGE_TO_CHAT='ADD_MESSAGE_TO_CHAT';
export const UPDATE_STATUS_MESSAGE='UPDATE_STATUS_MESSAGE';

